# Generated by Django 2.0.10 on 2019-02-13 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0006_image_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow')], max_length=20)),
                ('notification_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_from', to=settings.AUTH_USER_MODEL)),
                ('notification_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
