# Generated by Django 2.0.10 on 2019-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190213_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
